# COntenedor


In [14]:
import numpy as np
import math as mt

from time import sleep
from IPython.display import clear_output
import string


In [128]:

class container:
    count_container = 0
    RTG = np.zeros((6,6), dtype = np.int8)
    RTG_Names =  [['' for i in range(6)] for j in range(6)]
    print('Disposición actual')
    print(RTG, '\n\n')
    
    def __init__(self, name, pos):   #inicializador
        self.name = name
        self.pos = pos
        self.see_RTG(self.pos, 0)
        
    def write_name(self, pos):
        self.RTG_Names[pos[0]][pos[1]] = self.name
    
        
    @classmethod
    def print_name(cls):
        print(cls.RTG_Names)
    
    
    def RTG_write(self,pos,mode): #Escribe un contenedor en la posición deseada
        self.RTG[pos[0]][pos[1]] = 1
        self.pos = pos 
        self.write_name(pos)
        if mode == 0:
            self.print_RTG()
        
    @classmethod
    def print_RTG(cls):
        clear_output()
        print('Disposición actual\n', cls.RTG)  
        sleep(1)
    

    def see_RTG(self, pos, move): #Revisa la disponibilidad del contenedor
        mtx = self.RTG
        aux_in, aux_out= 1, 0
        possible = False
        mode = 0
        
        if move == 1:
            move = 0
            mode = 1
        
        while aux_in != aux_out:  
            
            if move == 0:
                if pos[0] == 5 and mtx[pos[0]][pos[1]] == 0: #si la posición de abajo está vacia, se crea contenedor
                    aux_out = aux_in
                    possible = True 
                    
                elif mtx[pos[0]][pos[1]] == 0 and mtx[pos[0]+1][pos[1]] == 1: 
                    aux_out = aux_in
                    possible = True                
                        
                elif mtx[pos[0]][pos[1]] == 1 or mtx[pos[0]+1][pos[1]] == 0:
                    aux_out = aux_in
                    clear_output()
                    print("Posición inválida")
                    print('Disposición actual')
                    print(self.RTG, '\n\n')
        
        if move == 0 and possible == True:
            self.RTG_write(pos, mode)
            
        
        return possible        
    
    def move(self, pos):
        mtx = self.RTG
        pos_in = self.pos
        pos_out = pos
        print('Moviendo')
        
        if mtx[pos_in[0]-1][pos_in[1]] == 0:
            possible = self.see_RTG(pos, 1)
        else:
            print('No es posible mover')
            sleep(1.5)
            clear_output()
            print('Disposición actual\n', mtx)  
            possible = False
        
        if possible == True:
            self.RTG[pos_in[0]][pos_in[1]] = 0
            self.RTG_write(pos_out, mode = 1) 
            self.print_RTG()
    
    @classmethod
    def add_container(cls):
        cls.count_container += 1

    @classmethod
    def clear_RTG(cls):
        cls.RTG = np.zeros((6,6), dtype = np.int8)
        

Disposición actual
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 




In [129]:
names = list(string.ascii_lowercase)
cont = []
y = 0
container.clear_RTG()

for i in range(1):
    for j in range(6):
        cont.append( container(names[y], [abs(i-5), abs(j)]) )
        y += 1

cont[5].move([4,1])
cont[5].move([4,3])
cont[5].move([4,4])
cont[4].move([4,2])
# c1 = container([5,0])
# c2 = container([5,1])
# c3 = container([4,1])
# c2.move([5,4])


Disposición actual
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [1 1 1 1 1 0]]


cont[7].

#print(container.print_name())

In [118]:

arr =  np.arange(35, -1, -1)
arr = arr.reshape(6, 6)

print(arr)

        


[[35 34 33 32 31 30]
 [29 28 27 26 25 24]
 [23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]
