# Contenedor


In [2]:
import numpy as np
import math as mt
from time import sleep
from IPython.display import clear_output


In [33]:

class container:
    count_container = 0
    RTG = np.zeros((6,6), dtype = np.int8)
    print('Disposición actual')
    print(RTG, '\n\n')
    
    def __init__(self, pos):   #inicializador
        self.pos = pos
        container.see_RTG(self.pos, 0)
        
    
    @classmethod
    def RTG_write(cls,pos,mode): #Escribe un contenedor en la posición deseada
        cls.RTG[pos[0]][pos[1]] = 1 
        if mode == 0:
            container.print_RTG()
        
    @classmethod
    def print_RTG(cls):
        clear_output()
        print('Disposición actual\n', cls.RTG)  
        sleep(1.5)
    
    @classmethod
    def see_RTG(cls, pos, move): #Revisa la disponibilidad del contenedor
        mtx = cls.RTG
        (y, x) = mtx.shape
        aux_in, aux_out= 1, 0
        possible = False
        mode = 0
        
        while aux_in != aux_out:  
            
            if move == 0:
                if pos[0] == 5 and mtx[pos[0]][pos[1]] == 0: #si la posición de abajo está vacia, se crea contenedor
                    aux_out = aux_in
                    possible = True 
                    
                elif mtx[pos[0]][pos[1]] == 0 and mtx[pos[0]+1][pos[1]] == 1: 
                    aux_out = aux_in
                    possible = True                
                        
                elif mtx[pos[0]][pos[1]] == 1 or mtx[pos[0]+1][pos[1]] == 0:
                    aux_out = aux_in
                    print("Posición inválida")
                    print('Disposición actual')
                    print(cls.RTG, '\n\n')
            
            elif move == 1:
                
                if mtx[pos[0]-1][pos[1]] == 0:
                    move = 0
                    mode = 1
                else:
                    print('No es posible mover')
                    possible = False
                    aux_out = aux_in
        
        if move == 0 and possible == True:
            container.RTG_write(pos, mode)
        
        return possible        
    
    def move(self, pos):
        pos_in = self.pos
        pos_out = pos
        print('Moviendo')
        possible = container.see_RTG(pos, 1)
        
        if possible == True:
            self.RTG[pos_in[0]][pos_in[1]] = 0
            container.RTG_write(pos_out, mode = 1) 
            container.print_RTG()
    
    @classmethod
    def add_container(cls):
        cls.count_container += 1

    @classmethod
    def clear_RTG(cls):
        cls.RTG = np.zeros((6,6), dtype = np.int8)
        

Disposición actual
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]] 




In [ ]:
  # @classmethod #Parece tetris
    # def see_RTG(cls, i, pos): #Revisa la disponibilidad del contenedor
    #     mtx = cls.RTG
    #     (y, x) = mtx.shape
    #     aux_in, aux_out= 1, 0
        
    #     while aux_in != aux_out:  
    #         if i == 5 and mtx[i][pos[1]] == 0: #si la posición de abajo está vacia, se crea contenedor
    #             aux_out = aux_in
    #             print('Creando container en posición: ', i, pos[1])
    #             container.add_container()
    #             container.RTG_write(i, pos)
                
                
    #         elif mtx[i][pos[1]] == 0 and mtx[i+1][pos[1]] == 1: 
    #                 aux_out = aux_in
    #                 print('Creando container en posición: ', i, pos[1])
    #                 container.add_container()
    #                 container.RTG_write(i,pos)
                    
    #         elif i > y or mtx[i][pos[1]] == 1:
    #             aux_out = aux_in
    #             print("Posición inválida")
    #             print('Disposición actual')
    #             print(cls.RTG, '\n\n')
    #         i -= 1 
            

In [34]:
container.clear_RTG()
c1 = container([5,0])
c2 = container([5,1])
c3 = container([4,1])
c1.move([5,4])


Disposición actual
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [1 1 0 0 1 0]]
